apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: strongswan-deployment
  labels:
    app: strongswan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongswan
  template:
    metadata:
      labels:
        app: strongswan
    spec:
      containers:
      - name: couchbase-strongswan
        image: couchbase/strongswan:1.0.0
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - name: isakmp
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat-t
          containerPort: 4500
          protocol: UDP
        env:
        - name: STRONGSWAN_LEFTID
          value: aws-us-east
        - name: STRONGSWAN_RIGHT
          value: 85.254.56.102
        - name: STRONGSWAN_RIGHTID
          value: aws-us-west
        - name: STRONGSWAN_RIGHTSUBNET
          value: 10.1.0.0/16
        - name: STRONGSWAN_PSK
          value: supersecret

        
